### ISSUE TITLE
Mojs curve editor issue : hidden curve beyond boundaries

### ISSUE THREAD

**Issue by lansolo99** [legomushroom/mojs-curve-editor#17]
Hi,

I encounter an issue when editing the curve when it goes beyond the boundaries (below 0, and above 1 axis) as showed in the attached screen : it's hidden.

I imported it using the cdn method. Thanks if you have a workaround to deal with this.
![curve_editor](https://user-images.githubusercontent.com/10405016/28706282-e3ec54b0-7373-11e7-877d-7c292b8e9797.jpg)

**Comment by legomushroom** [comment]
Hi @lansolo99!

Thanks for the issue! This looks weird and should never happen so this is certainly a `bug`. Can you provide more info regarding `OS`/`browser` you use or any reproduction step to catch it locally? Is the bug consistent for you? Do you see any errors in the console?

Thanks a lot!

**Comment by xavierfoucrier** [comment]
Hi @lansolo99,

Can you provide browser/OS in order for us to investigate?
Otherwise this issue will be considered outdated and closed.

Thanks a lot!

**Comment by lansolo99** [comment]
Hi @legomushroom It's been ages I opened this issue 😀 

I thought mos.js was not maintained anymore, it was probably using Chrome but you can consider closing this issue as I don't plan to follow up on this problem.

**Comment by xavierfoucrier** [comment]
Hello @lansolo99,

Merci / Thanks for your feedback!
I will close this and reopen if someone face it again.

> As you guessed, mojs was not maintained during a small period back in 2016/2017 because Oleg Solomka has moved to Microsoft, then Github core team, that's why. Since 2017 the project is still maintained, and the v1 should be released very soon :wink:
