### ISSUE TITLE
Joint Creation on line click

### ISSUE THREAD

**Issue by zfrisch** [legomushroom/mojs-curve-editor#2]
Hello! 

I tested out the curve editor on the newest IE, Chrome, and FireFox. It works great in FireFox, but the other two browsers seem to have an issue that when you highlight and click on the initial line itself, it will create a new line and jump out of the bounds of the grid and onto the page.
I was testing it here: 

http://codepen.io/zfrisch/pen/KgybAj

![image](https://cloud.githubusercontent.com/assets/16858621/19085308/8efeec98-8a2f-11e6-9eb8-b6db4a29c4bb.png)

![image](https://cloud.githubusercontent.com/assets/16858621/19085354/ab70fe34-8a2f-11e6-8f4c-1abe4f247c70.png)

**Comment by legomushroom** [comment]
@zfrisch hi, sorry about that and thanks for the alert! The issue has been solved in `dev` branch and will be released soon. Here is the current version of the `CurveEditor` [codepen example](http://codepen.io/sol0mka/pen/qaVgjx) - it has the issue when you have to reload the page just after you have added the new point. I will try to release all updates this week.

**Comment by zfrisch** [comment]
@legomushroom Awesome, thanks! :smile:

**Comment by legomushroom** [comment]
Just released `1.4.3` version which solves the issue. 🎉 Thanks for the alert!

**Comment by legomushroom** [comment]
Hi Zak!

Just realised that it is you - the best supporter of the project on Patreon! Thank you so much for your support, much appreciated!

I should say that the reward is on the way to you. Do you have any twitter account to be listed on the `mojs` repo? Or you would prefer `github` username? Please let me know.

Thank you again! Cheers!

**Comment by zfrisch** [comment]
Linking my github username would be great, thanks for asking! 

It's my pleasure to donate! I really love the idea of this library. I've been following it since your demo on Codepen and I can tell that you've been consistently working hard to add new features and functionality whenever you have an opportunity. It's very impressive, especially considering that you mentioned on Patreon that you have other obligations outside of this project, and I'm all too happy to help out any way I can!

**Comment by legomushroom** [comment]
Thanks a lot! Will do my best maintaining the project!

BTW just release video on vimeo with `mojs-curve-editor`, check it out!
https://vimeo.com/185587462
