### ISSUE TITLE
Error when adding startPath

### ISSUE THREAD

**Issue by danvoyce** [legomushroom/mojs-curve-editor#20]
When I specify a value that I previously copied from the editor

```
const mojsCurve = new MojsCurveEditor({
  startPath: 'M0, 100 C0, 100 100, 0 100, 0',
});
```

I get the following error
```
mojs-curve-editor.js:13544 Error: <path> attribute d: Expected number, "M0, 100 C0, 100 N aN, N aN 100, …".
```

I'm using the latest version of Chrome (61.0.3163.100) and I've pulled directly from Github rather than using NPM where the code seems to say it's version 1.5.0 but it's not the same as it is here on Github

**Comment by danvoyce** [comment]
So been doing some digging and have fixed this by ensuring the `tempX` and `tempY` values in `calculate-point.js` aren't `NaN`, as well as `angle` in `point-to-angle.js`. Some 0/0 been going on...

However all I am doing is setting these values to 0 if they are falsey, which obviously is not the correct solution. Now when trying to translate the handles, they don't move until mouse up. My guess is we need to be updating `tempX` and `tempY` to the `mouseX` and `mouseY`, but I'm a bit lost now tbh. If you can give me some pointers I'll be happy to dig some more!

**Comment by xavierfoucrier** [comment]
This will be fixed in the next release :tada:
