### ISSUE TITLE
Bezier curves support appears broken

### ISSUE THREAD

**Issue by processprocess** [legomushroom/mojs-curve-editor#27]
Upon activating a bezier curve on a point, an `"Expected number"` error is thrown.

the `startPath` throws this on load.
Clearing the path with `shift + option` +  pressing `\` 3 times, then creating a new control point, then activating the bezier curve also throws the error.

![Mar-10-2021 22-17-53](https://user-images.githubusercontent.com/3860311/110730572-ab3c7e00-81ee-11eb-8149-233a00352c2e.gif)

**Comment by xavierfoucrier** [comment]
Hi @processprocess,

This is related to our internal API changes and will be fix within `v1.0.0` release.
Please be patient and stay tuned!

Closing the issue.
