### ISSUE TITLE
error on initialize

### ISSUE THREAD

**Issue by enl31** [legomushroom/mojs-curve-editor#4]
Hi, i have an error in initiating curve editor:

in console i have:

> Uncaught Error: MojsPlayer expects Tween/Timeline/Module as `add` option in constructor call. [ new MojsPlayer({ add: new mojs.Tween }); ]

this is my code:

```
import MojsPlayer from 'mojs-player';
import MojsCurveEditor from 'mojs-player';

const mojsCurve = new MojsCurveEditor({
    name:         'bounce curve',
    isSaveState:  true
  });

```

and here is my gulp compile task:

```

gulp.task('js', ()=> {
  return gulp
  .src('src/fx.js')
  .pipe(webpack({
    module: {
      loaders: [
      {
        test: /\.jsx?$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        query: {
          presets: ["stage-0" , "es2015"]
        }
      }
      ],
    },
    output: {
      filename: 'fx.js',
    },
  }))
  .on('error', handleError)
  .pipe(gulp.dest('dist/js/'))
  .pipe(browserSync.reload({
    stream: true
  }));
});
```

can you help me out? appreciate any help. thank you...

**Comment by legomushroom** [comment]
Hi @enl31! Sorry about the troubles! Seems like you've missed with the `import MojsCurveEditor from 'mojs-player';` statement, it should be `import MojsCurveEditor from 'mojs-curve-editor';`

Cheers!

**Comment by enl31** [comment]
Hi. 
I copied the _import_ code from your readme. so if you think that is wrong please change it.
I used the import code like this and its working:
`import MojsCurveEditor from 'mojs-curve-editor';`
thank you so much

**Comment by legomushroom** [comment]
@enl31 totally my fault, thanks for the alert!

**Comment by enl31** [comment]
@legomushroom thank you. by the way awesome work. i wish you and your team the best.

**Comment by legomushroom** [comment]
@enl31 thanks! 👍

**Comment by enl31** [comment]
Dear @legomushroom i think you should change the alternative way too...
`const MojsCurveEditor = require('mojs-player').default;`
to
`const MojsCurveEditor = require('mojs-curve-editor').default;`

thank you.

**Comment by legomushroom** [comment]
@enl31 hah! thanks again!
