### ISSUE TITLE
Curve hiding when used with normalise.css

### ISSUE THREAD

**Issue by ghost** [legomushroom/mojs-curve-editor#7]
![screen shot 2016-11-21 at 11 48 58](https://cloud.githubusercontent.com/assets/13697714/20487270/9fafc7c4-affa-11e6-8f56-33d45034251d.png)

Had issues with the curve hiding above 1 and below 0 (see attached) so dug into the code and found a conflict with normalise.css. Normalise is adding overflow: hidden to svg:not(:root) which is hiding the curve.

**Comment by legomushroom** [comment]
Thanks, Bruce! 👍

**Comment by nwalton3** [comment]
Added pull request #9 to fix this issue

**Comment by legomushroom** [comment]
thank you!
